// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0PGzjLU7P2FVcAYKGDwOa97Kf-IN-pI8',
    appId: '1:980547744849:web:1e8b6a9e694d8f8346b470',
    messagingSenderId: '980547744849',
    projectId: 'barista-4d00e',
    authDomain: 'barista-4d00e.firebaseapp.com',
    storageBucket: 'barista-4d00e.appspot.com',
    measurementId: 'G-2SJLCZB9CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdiFydky11b0GyXGL6Im3q29OvMzdLA9A',
    appId: '1:980547744849:android:ae16d2cd470b207746b470',
    messagingSenderId: '980547744849',
    projectId: 'barista-4d00e',
    storageBucket: 'barista-4d00e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXnqIc304UQ8rXabrN2CKI7zrtyCMH_T8',
    appId: '1:980547744849:ios:b99df59beca222a346b470',
    messagingSenderId: '980547744849',
    projectId: 'barista-4d00e',
    storageBucket: 'barista-4d00e.appspot.com',
    iosBundleId: 'com.barista.privateWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXnqIc304UQ8rXabrN2CKI7zrtyCMH_T8',
    appId: '1:980547744849:ios:954c513eeaf3e7df46b470',
    messagingSenderId: '980547744849',
    projectId: 'barista-4d00e',
    storageBucket: 'barista-4d00e.appspot.com',
    iosBundleId: 'com.example.barista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0PGzjLU7P2FVcAYKGDwOa97Kf-IN-pI8',
    appId: '1:980547744849:web:d9fdd8fa402287fa46b470',
    messagingSenderId: '980547744849',
    projectId: 'barista-4d00e',
    authDomain: 'barista-4d00e.firebaseapp.com',
    storageBucket: 'barista-4d00e.appspot.com',
    measurementId: 'G-F6PL022F9M',
  );
}
